// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRwlxaBFx3SO3PfljxpV3DnKgYX_AyxEI',
    appId: '1:817877824146:web:9264363dad314a83a8ec4b',
    messagingSenderId: '817877824146',
    projectId: 'etoil-app',
    authDomain: 'etoil-app.firebaseapp.com',
    storageBucket: 'etoil-app.appspot.com',
    measurementId: 'G-GXFGMFW7GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdjTVNPwj2Ji0QkG1KLMpk96NFZXSLWDA',
    appId: '1:817877824146:android:c45e1e5f5e89521da8ec4b',
    messagingSenderId: '817877824146',
    projectId: 'etoil-app',
    storageBucket: 'etoil-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc220y-GLQiOJhnCopLDOnq70sOymDknE',
    appId: '1:817877824146:ios:224f6dfa8b4948b2a8ec4b',
    messagingSenderId: '817877824146',
    projectId: 'etoil-app',
    storageBucket: 'etoil-app.appspot.com',
    iosBundleId: 'com.example.etoileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc220y-GLQiOJhnCopLDOnq70sOymDknE',
    appId: '1:817877824146:ios:224f6dfa8b4948b2a8ec4b',
    messagingSenderId: '817877824146',
    projectId: 'etoil-app',
    storageBucket: 'etoil-app.appspot.com',
    iosBundleId: 'com.example.etoileApp',
  );
}
